---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-ui-codebase
  description: A UI for browsing products and making purchases
spec:
  type: library
  lifecycle: production
  owner: storefront-team
  system: ecommerce-site
  consumesApi:
  - storefront-inventory-codebase
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-inventory-codebase
  description: A UI for browsing products and making purchases
spec:
  type: library
  lifecycle: production
  owner: inventory-team
  system: ecommerce-site
  providesApi:
  - storefront-inventory-codebase
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ecommerce-site
  description: E-Commerce site
spec:
  owner: ecommerce-eng-team

### TONS of User entites representing your corp directory...