---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-ui-3781ae # name of the running TAS app, but uniqueify? 
  description: Running TAS app of "A UI for browsing products and making purchases" # this is copied from the codebase it's connected to?
  links:
    - url: https://apps.sys.domain/apps/237821287237823782
      title: AppsManager
      icon: dashboard
      type: admin-dashboard
    - url: https://storefront.apps.domain
      title: Route
      icon: web
spec:
  type: website # TAS can't always tell if something is a website or service, we can make one default (or guess maybe sometimes?)
  lifecycle: production # inherited from the foundation where it's running?
  owner: space-storefront-ui # dynamically available from the TAS foundation
  system: space-storefront-ui # group everything in the space as vizualizable?
  dependsOn:
    - component:storefront-inventory-5737cd # NOT SURE exactly how we can know that the UI app depends on the inventory service app, SCS?, C2C networking? We can also use codebase dependencies
    - component:storefront-ui-codebase # reference to the codebase entity. when "cf push" was run, this name was given in a label to "link" the running app to this pre-defined codebase
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-inventory-5737cd
  description: Backend service for tracking inventory and processing payment 
spec:
  type: service
  lifecycle: production
  owner: space-storefront-ui
  system: space-storefront-ui
  dependsOn:
    - component:storefront-inventory-codebase
    - resource:inventory-mysql-db # a TAS brokered service that was bound at runtime
    - resource:payment-processor # a TAS user provided service to something external that the app uses, TAS shouldn't generate a "Resource" entity for this
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inventory-mysql-db
  description: Instance of mysql large plan in space ecommerce-inventory 
spec:
  owner: space-storefront-ui
  type: mysql-database # knowing a stronger type like "database" involves categorizing various service broker types
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: space-storefront-ui
spec:
  owner: space-storefront-ui
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: space-storefront-ui
  description: SpaceDevelopers+ in space storefront-ui
spec:
  type: app-operators # team is the other option that makes sense here, but it's a strong word for a group of spacedev+ folks
  children: []
  members: # email addresses of space devs from TAS
  - stevensonda_vmware.com # these are references to external entites
  - gcobb_vmware.com
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: org-ecommerce
  description: OrgManagers+ in org blah
spec:
  type: organization-management
  children:
  - space-storefront-ui
  members: # email addresses of org managers from TAS
  - hrajagopal_vmware.com # these are references to external entites